### ISSUE TITLE
访问首页报“无效的token”错误

### ISSUE THREAD

**Issue by netstar2011** [WeBankBlockchain/WeBASE-Web#374]
按文档中的说明，分别按两次，第一次一键部署了“fisco-node"，第二次一键部署"WeBASE-Web"，部署无错误信息，部署后一键启动“python3 deploy.py startAll”所有模块运行正常。
操作系统：CentOS Linux release 7.6.1810 (Core) 
数据库：mysql  Ver 8.0.26 for Linux on x86_64 (MySQL Community Server - GPL)
JDK ： java 13.0.2 2020-01-14
访问首页管理节点报错，错误信息如下：
[ERROR][2021-07-22 10:16:02.279][http-nio-5001-exec-8][wsweb][2224][2224][LOG_POINT]not found token
[ERROR][2021-07-22 10:16:02.280][http-nio-5001-exec-8][wsweb][2224][2224][LOG_POINT]catch business exception:[]
com.webank.webase.node.mgr.base.exception.NodeMgrException: invalid token
	at com.webank.webase.node.mgr.base.tools.NodeMgrTools.getToken(NodeMgrTools.java:461) ~[WeBASE-Node-Manager.jar:?]
	at com.webank.webase.node.mgr.account.AccountService.getCurrentAccount(AccountService.java:266) ~[WeBASE-Node-Manager.jar:?]
	at com.webank.webase.node.mgr.base.filter.AccountFilter.preHandle(AccountFilter.java:38) ~[WeBASE-Node-Manager.jar:?]
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:137) ~[spring-webmvc-5.1.16.RELEASE.jar:5.1.16.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1035) [spring-webmvc-5.1.16.RELEASE.jar:5.1.16.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.1.16.RELEASE.jar:5.1.16.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.1.16.RELEASE.jar:5.1.16.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) [spring-webmvc-5.1.16.RELEASE.jar:5.1.16.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-embed-core-9.0.36.jar:9.0.36]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.1.16.RELEASE.jar:5.1.16.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.36.jar:9.0.36]

**Comment by hsycc** [comment]
mysql版本建议在5.7 以下， 5.7版本及以上需要禁用only_full_group_by

查看node-mgr的报错日志， 数据库是否正确链接
 tail -f log/WeBASE-Node-Manager-error.log 

检查 webaee-node-mgr/conf/application.yml 配置是否正确被替换

一键部署的脚本， 个人的配置信息，如sql 账号密码， 带有 & 以及类似的特殊符号，

**Comment by CodingCattwo** [comment]
已在最新版本中修复了only_full_group_by的兼容问题
